# Generated by Django 4.2.4 on 2024-07-17 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Pseudo'),
        ),
    ]
